---

- name: ensure ntp package is absent
  package:
    name: ntp
    state: absent
  tags:
    - chrony
    - time
    - package
    - service
    - install

- name: ensure chrony requirements packages are installed
  package:
    name: "{{ item }}"
    state: "{{ chrony_package_state }}"
  with_items: "{{ chrony_pre_packages }}"
  when: chrony_pre_packages|length > 0
  tags:
    - chrony
    - time
    - package
    - service
    - install

- name: ensure chrony packages are installed
  package:
    name: "{{ item }}"
    state: "{{ chrony_package_state }}"
  with_items: "{{ chrony_packages }}"
  when: chrony_packages|length > 0
  tags:
    - chrony
    - time
    - package
    - service
    - install

- name: update chrony.conf from template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  with_items:
    - {src: "chrony.conf.j2", dest: "{{ chrony_config_path }}/chrony.conf"}
    - {src: "conf.d_ansible.conf.j2", dest: "{{ chrony_config_path }}/conf.d/ansible.conf"}
  notify: restart chrony
  tags:
    - chrony
    - time
    - package
    - config

- name: update sources from template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  with_items:
    - {src: "sources.d_ansible.sources.j2", dest: "{{ chrony_config_path }}/sources.d/ansible.sources"}
  notify: reload chronyc
  tags:
    - chrony
    - time
    - package
    - config

# vim: syntax=yaml ts=2 sw=2 et sr softtabstop=2 autoindent
